import type { Metadata } from "next";

import Header from "@/components/header";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Services - Domopan",
  description: "Generated by create next app",
};

export default function ServicesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="bg-(--frosted-sky) relative min-h-dvh flex flex-col justify-between pb-6">
      {children}
    </main>
  );
}
