import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "Projects - Domopan",
  description: "Generated by create next app",
};

export default function ProjectsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <main className="bg-black relative min-h-dvh">{children}</main>;
}
