import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Info - Domopan",
  description: "Generated by create next app",
};

export default function InfoLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="bg-(--soft-pistachio) relative min-h-dvh flex flex-col justify-between pb-6">
      {children}
    </main>
  );
}
