import type { Metadata } from "next";
import "../globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Info - Domopan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="bg-(--soft-pistachio) relative min-h-dvh flex flex-col justify-between pb-6">
      <Header />
      {children}

      <Footer />
    </main>
  );
}
