import { CLOUDINARY_BASE } from "@/lib/cloudinary";
import AlthurayaTowerElement from "@/public/althuraya/al_thuraya_tower.jpg";
import AlthurayaTower1Element from "@/public/althuraya/al_thuraya_tower_other1.jpg";
import AlthurayaTower2Element from "@/public/althuraya/al_thuraya_tower_other2.jpg";
import DohaCollegeElement from "@/public/dohacollege/doha_college.jpg";
import LakhwiyaStadiumElement from "@/public/lakhwiya/lakhwiya_stadium.jpg";
import LakhwiyaStadiumElement1 from "@/public/lakhwiya/lakhwiya_stadium_other1.jpg";
import LakhwiyaStadiumElement2 from "@/public/lakhwiya/lakhwiya_stadium_other2.jpg";
import LakhwiyaStadiumElement3 from "@/public/lakhwiya/lakhwiya_stadium_other3.jpg";
import LakhwiyaStadiumElement4 from "@/public/lakhwiya/lakhwiya_stadium_other4.jpg";
import LakhwiyaStadiumElement5 from "@/public/lakhwiya/lakhwiya_stadium_other5.jpg";
import UmSalalElement1 from "@/public/ummsalal/um_salal_health_center_other1.jpg";
import UmSalalElement10 from "@/public/ummsalal/um_salal_health_center_other10.jpg";
import UmSalalElement2 from "@/public/ummsalal/um_salal_health_center_other2.jpg";
import UmSalalElement3 from "@/public/ummsalal/um_salal_health_center_other3.jpg";
import UmSalalElement4 from "@/public/ummsalal/um_salal_health_center_other4.jpg";
import UmSalalElement5 from "@/public/ummsalal/um_salal_health_center_other5.jpg";
import UmSalalElement6 from "@/public/ummsalal/um_salal_health_center_other6.jpg";
import UmSalalElement7 from "@/public/ummsalal/um_salal_health_center_other7.jpg";
import UmSalalElement8 from "@/public/ummsalal/um_salal_health_center_other8.jpg";
import UmSalalElement9 from "@/public/ummsalal/um_salal_health_center_other9.jpg";
import UmSalalElement from "@/public/ummsalal/umm_salal_health_center_main.jpg";

export const AlthurayaTowerMainImage = AlthurayaTowerElement;
export const AlthurayaTowerImage1 = AlthurayaTower1Element;
export const AlthurayaTowerrImage2 = AlthurayaTower2Element;

export const AlwajbaMainImage = `${CLOUDINARY_BASE}/alwajba-main_kkvhvi`;
export const AlwajbaImage1 = `${CLOUDINARY_BASE}/alwajba-other1_m3q5ih`;
export const AlwajbaImage2 = `${CLOUDINARY_BASE}/alwajba-other2_iwjwug`;
export const AlwajbaImage3 = `${CLOUDINARY_BASE}/alwajba-other3_gamnjc`;
export const AlwajbaImage4 = `${CLOUDINARY_BASE}/alwajba-other4_b1upbl`;
export const AlwajbaImage5 = `${CLOUDINARY_BASE}/alwajba-other5_cxirkl`;
export const AlwajbaImage6 = `${CLOUDINARY_BASE}/alwajba-other6_nvrzrz`;
export const AlwajbaImage7 = `${CLOUDINARY_BASE}/alwajba-other7_katide`;
export const AlwajbaImage8 = `${CLOUDINARY_BASE}/alwajba-other8_d2ozlo`;
export const AlwajbaImage10 = `${CLOUDINARY_BASE}/alwajba-other10_cqd8bt`;

export const DohaMainImage = DohaCollegeElement;
export const DohaImage1 = `${CLOUDINARY_BASE}/doha-college-campus-other1_ziglpv`;
export const DohaImage2 = `${CLOUDINARY_BASE}/doha-college-campus-other2_pjncec`;
export const DohaImage3 = `${CLOUDINARY_BASE}/doha-college-campus-other3_iqcdeg`;
export const DohaImage4 = `${CLOUDINARY_BASE}/doha-college-campus-other4_hduoj2`;
export const DohaImage5 = `${CLOUDINARY_BASE}/doha-college-campus-other5_hhczqg`;
export const DohaImage6 = `${CLOUDINARY_BASE}/doha-college-campus-other6_xrwax8`;

export const LakhwiyaStadiumMainImage = LakhwiyaStadiumElement;
export const LakhwiyaStadiumImage1 = LakhwiyaStadiumElement1;
export const LakhwiyaStadiumImage2 = LakhwiyaStadiumElement2;
export const LakhwiyaStadiumImage3 = LakhwiyaStadiumElement3;
export const LakhwiyaStadiumImage4 = LakhwiyaStadiumElement4;
export const LakhwiyaStadiumImage5 = LakhwiyaStadiumElement5;

export const ShazaMainImage = `${CLOUDINARY_BASE}/shaza-main-image_te12ui`;
export const ShazaImage1 = `${CLOUDINARY_BASE}/shaza-other1_j0tt9i`;
export const ShazaImage2 = `${CLOUDINARY_BASE}/shaza-other2_quygoa`;
export const ShazaImage3 = `${CLOUDINARY_BASE}/shaza-other3_ldglve`;
export const ShazaImage4 = `${CLOUDINARY_BASE}/shaza-other4_hfcda3`;
export const ShazaImage5 = `${CLOUDINARY_BASE}/shaza-other5_f9qu1u`;
export const ShazaImage6 = `${CLOUDINARY_BASE}/shaza-other6_qztyp0`;

export const UmsalalMainImage = UmSalalElement;
export const UmsalalImage1 = UmSalalElement1;
export const UmsalalImage2 = UmSalalElement2;
export const UmsalalImage3 = UmSalalElement3;
export const UmsalalImage4 = UmSalalElement4;
export const UmsalalImage5 = UmSalalElement5;
export const UmsalalImage6 = UmSalalElement6;
export const UmsalalImage7 = UmSalalElement7;
export const UmsalalImage8 = UmSalalElement8;
export const UmsalalImage9 = UmSalalElement9;
export const UmsalalImage10 = UmSalalElement10;
