import AlthurayaTowerElement from "@/public/althuraya/al_thuraya_tower.jpg";
import AlthurayaTower1Element from "@/public/althuraya/al_thuraya_tower_other1.jpg";
import AlthurayaTower2Element from "@/public/althuraya/al_thuraya_tower_other2.jpg";
import AlwajbaElement from "@/public/alwajba/alwajba.jpg";
import Alwajba1Element from "@/public/alwajba/alwajba_other1.jpg";
import Alwajba2Element from "@/public/alwajba/alwajba_other2.jpg";
import Alwajba3Element from "@/public/alwajba/alwajba_other3.jpg";
import Alwajba4Element from "@/public/alwajba/alwajba_other4.jpg";
import Alwajba5Element from "@/public/alwajba/alwajba_other5.jpg";
import Alwajba6Element from "@/public/alwajba/alwajba_other6.jpg";
import Alwajba7Element from "@/public/alwajba/alwajba_other7.jpg";
import Alwajba8Element from "@/public/alwajba/alwajba_other8.jpg";
import Alwajba9Element from "@/public/alwajba/alwajba_other9.jpg";
import Alwajba10Element from "@/public/alwajba/alwajba_other10.jpg";
import DohaCollegeElement from "@/public/dohacollege/doha_college.jpg";
import DohaCollege1Element from "@/public/dohacollege/doha_college_other1.jpg";
import DohaCollege2Element from "@/public/dohacollege/doha_college_other2.jpg";
import LakhwiyaStadiumElement from "@/public/lakhwiya/lakhwiya_stadium.jpg";
import LakhwiyaStadiumElement1 from "@/public/lakhwiya/lakhwiya_stadium_other1.jpg";
import LakhwiyaStadiumElement2 from "@/public/lakhwiya/lakhwiya_stadium_other2.jpg";
import LakhwiyaStadiumElement3 from "@/public/lakhwiya/lakhwiya_stadium_other3.jpg";
import LakhwiyaStadiumElement4 from "@/public/lakhwiya/lakhwiya_stadium_other4.jpg";
import LakhwiyaStadiumElement5 from "@/public/lakhwiya/lakhwiya_stadium_other5.jpg";
import ShazaElement from "@/public/shaza/shaza_kempinski_main.jpg";
import ShazaElement1 from "@/public/shaza/shaza_kempinski_other1.jpg";
import ShazaElement2 from "@/public/shaza/shaza_kempinski_other2.jpg";
import ShazaElement3 from "@/public/shaza/shaza_kempinski_other3.jpg";
import ShazaElement4 from "@/public/shaza/shaza_kempinski_other4.jpg";
import ShazaElement5 from "@/public/shaza/shaza_kempinski_other5.jpg";
import ShazaElement6 from "@/public/shaza/shaza_kempinski_other6.jpg";
import UmSalalElement from "@/public/ummsalal/umm_salal_health_center_main.jpg";
import UmSalalElement1 from "@/public/ummsalal/um_salal_health_center_other1.jpg";
import UmSalalElement2 from "@/public/ummsalal/um_salal_health_center_other2.jpg";
import UmSalalElement3 from "@/public/ummsalal/um_salal_health_center_other3.jpg";
import UmSalalElement4 from "@/public/ummsalal/um_salal_health_center_other4.jpg";
import UmSalalElement5 from "@/public/ummsalal/um_salal_health_center_other5.jpg";
import UmSalalElement6 from "@/public/ummsalal/um_salal_health_center_other6.jpg";
import UmSalalElement7 from "@/public/ummsalal/um_salal_health_center_other7.jpg";
import UmSalalElement8 from "@/public/ummsalal/um_salal_health_center_other8.jpg";
import UmSalalElement9 from "@/public/ummsalal/um_salal_health_center_other9.jpg";
import UmSalalElement10 from "@/public/ummsalal/um_salal_health_center_other10.jpg";

export const AlthurayaTowerMainImage = AlthurayaTowerElement;
export const AlthurayaTowerImage1 = AlthurayaTower1Element;
export const AlthurayaTowerrImage2 = AlthurayaTower2Element;

export const AlwajbaMainImage = AlwajbaElement;
export const AlwajbaImage1 = Alwajba1Element;
export const AlwajbaImage2 = Alwajba2Element;
export const AlwajbaImage3 = Alwajba3Element;
export const AlwajbaImage4 = Alwajba4Element;
export const AlwajbaImage5 = Alwajba5Element;
export const AlwajbaImage6 = Alwajba6Element;
export const AlwajbaImage7 = Alwajba7Element;
export const AlwajbaImage8 = Alwajba8Element;
export const AlwajbaImage9 = Alwajba9Element;
export const AlwajbaImage10 = Alwajba10Element;

export const DohaMainImage = DohaCollegeElement;
export const DohaImage1 = DohaCollege1Element;
export const DohaImage2 = DohaCollege2Element;

export const LakhwiyaStadiumMainImage = LakhwiyaStadiumElement;
export const LakhwiyaStadiumImage1 = LakhwiyaStadiumElement1;
export const LakhwiyaStadiumImage2 = LakhwiyaStadiumElement2;
export const LakhwiyaStadiumImage3 = LakhwiyaStadiumElement3;
export const LakhwiyaStadiumImage4 = LakhwiyaStadiumElement4;
export const LakhwiyaStadiumImage5 = LakhwiyaStadiumElement5;

export const ShazaMainImage = ShazaElement;
export const ShazaImage1 = ShazaElement1;
export const ShazaImage2 = ShazaElement2;
export const ShazaImage3 = ShazaElement3;
export const ShazaImage4 = ShazaElement4;
export const ShazaImage5 = ShazaElement5;
export const ShazaImage6 = ShazaElement6;

export const UmsalalMainImage = UmSalalElement;
export const UmsalalImage1 = UmSalalElement1;
export const UmsalalImage2 = UmSalalElement2;
export const UmsalalImage3 = UmSalalElement3;
export const UmsalalImage4 = UmSalalElement4;
export const UmsalalImage5 = UmSalalElement5;
export const UmsalalImage6 = UmSalalElement6;
export const UmsalalImage7 = UmSalalElement7;
export const UmsalalImage8 = UmSalalElement8;
export const UmsalalImage9 = UmSalalElement9;
export const UmsalalImage10 = UmSalalElement10;
